export type Tier = "platinum" | "gold" | "silver" | "bronze" | "redflag";

export interface CategoryScore {
  name: string;
  nameAr: string;
  score: number;
  emoji: string;
}

export interface Review {
  id: string;
  author: string;
  authorInitials: string;
  verified: boolean;
  date: string;
  rating: number;
  comment: string;
  commentAr?: string;
  businessResponse?: string;
  categories: CategoryScore[];
}

export interface Business {
  id: string;
  name: string;
  nameAr: string;
  sector: string;
  sectorAr: string;
  city: string;
  cityAr: string;
  tier: Tier;
  overallScore: number;
  reviewCount: number;
  rankChange: number;
  rank: number;
  logo: string;
  description: string;
  descriptionAr: string;
  verified: boolean;
  categories: CategoryScore[];
  reviews: Review[];
  featured?: boolean;
}

export const sectors = [
  { id: "all", label: "All Sectors", labelAr: "جميع القطاعات" },
  { id: "telecom", label: "Telecom", labelAr: "اتصالات" },
  { id: "banking", label: "Banking", labelAr: "بنوك" },
  { id: "food", label: "Food & Dining", labelAr: "مطاعم" },
  { id: "retail", label: "Retail", labelAr: "تجزئة" },
  { id: "automotive", label: "Automotive", labelAr: "سيارات" },
  { id: "ecommerce", label: "E-Commerce", labelAr: "تجارة إلكترونية" },
];

export const cities = [
  { id: "all", label: "All Cities", labelAr: "جميع المدن" },
  { id: "riyadh", label: "Riyadh", labelAr: "الرياض" },
  { id: "jeddah", label: "Jeddah", labelAr: "جدة" },
  { id: "dammam", label: "Dammam", labelAr: "الدمام" },
  { id: "mecca", label: "Mecca", labelAr: "مكة" },
  { id: "medina", label: "Medina", labelAr: "المدينة" },
];

export const categoryLabels: CategoryScore[] = [
  { name: "Service Quality", nameAr: "جودة الخدمة", score: 0, emoji: "⭐" },
  { name: "Wait Time", nameAr: "وقت الانتظار", score: 0, emoji: "⏱️" },
  { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 0, emoji: "🤝" },
  { name: "Cleanliness", nameAr: "النظافة", score: 0, emoji: "✨" },
  { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 0, emoji: "💰" },
  { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 0, emoji: "📱" },
];

export const businesses: Business[] = [
  {
    id: "stc",
    name: "STC",
    nameAr: "STC",
    sector: "telecom",
    sectorAr: "اتصالات",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "platinum",
    overallScore: 4.7,
    reviewCount: 1420,
    rank: 1,
    rankChange: 2,
    logo: "S",
    description: "Saudi Telecom Company - Saudi Arabia's leading digital and telecom provider.",
    descriptionAr: "شركة الاتصالات السعودية - المزود الرقمي والاتصالي الرائد في المملكة العربية السعودية.",
    verified: true,
    featured: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.8, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 4.3, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.7, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.9, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.5, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 5.0, emoji: "📱" },
    ],
    reviews: [
      {
        id: "r1",
        author: "Mohammed Al-Rashidi",
        authorInitials: "MA",
        verified: true,
        date: "2024-03-10",
        rating: 5,
        comment: "Absolutely world-class service. The staff at the Riyadh Park branch were incredibly helpful and resolved my issue in under 10 minutes.",
        commentAr: "خدمة على مستوى عالمي. الموظفون في فرع الرياض بارك كانوا متعاونين جداً وحلوا مشكلتي في أقل من 10 دقائق.",
        businessResponse: "Thank you Mohammed! We strive to provide the best service experience across all branches.",
        categories: [
          { name: "Service Quality", nameAr: "جودة الخدمة", score: 5, emoji: "⭐" },
          { name: "Wait Time", nameAr: "وقت الانتظار", score: 5, emoji: "⏱️" },
          { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 5, emoji: "🤝" },
          { name: "Cleanliness", nameAr: "النظافة", score: 5, emoji: "✨" },
          { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4, emoji: "💰" },
          { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 5, emoji: "📱" },
        ],
      },
      {
        id: "r2",
        author: "Sarah Al-Otaibi",
        authorInitials: "SO",
        verified: true,
        date: "2024-03-08",
        rating: 4,
        comment: "Great network coverage everywhere in Riyadh. The app is smooth and billing is always accurate. Minor wait times during peak hours.",
        categories: [
          { name: "Service Quality", nameAr: "جودة الخدمة", score: 4, emoji: "⭐" },
          { name: "Wait Time", nameAr: "وقت الانتظار", score: 3, emoji: "⏱️" },
          { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 5, emoji: "🤝" },
          { name: "Cleanliness", nameAr: "النظافة", score: 5, emoji: "✨" },
          { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4, emoji: "💰" },
          { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 5, emoji: "📱" },
        ],
      },
      {
        id: "r3",
        author: "Khalid Bin Salman",
        authorInitials: "KS",
        verified: true,
        date: "2024-03-05",
        rating: 5,
        comment: "The MySTC app is genuinely one of the best utility apps in KSA. Everything is seamless. Top tier experience.",
        businessResponse: "We're thrilled you enjoy MySTC! We work hard to make your digital experience world-class.",
        categories: [
          { name: "Service Quality", nameAr: "جودة الخدمة", score: 5, emoji: "⭐" },
          { name: "Wait Time", nameAr: "وقت الانتظار", score: 5, emoji: "⏱️" },
          { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 5, emoji: "🤝" },
          { name: "Cleanliness", nameAr: "النظافة", score: 5, emoji: "✨" },
          { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 5, emoji: "💰" },
          { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 5, emoji: "📱" },
        ],
      },
      {
        id: "r4",
        author: "Fatimah Al-Zahrani",
        authorInitials: "FZ",
        verified: true,
        date: "2024-03-02",
        rating: 4,
        comment: "Excellent corporate services. Our company switched all 200+ lines to STC and it's been a smooth experience overall.",
        categories: [
          { name: "Service Quality", nameAr: "جودة الخدمة", score: 4, emoji: "⭐" },
          { name: "Wait Time", nameAr: "وقت الانتظار", score: 4, emoji: "⏱️" },
          { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 5, emoji: "🤝" },
          { name: "Cleanliness", nameAr: "النظافة", score: 5, emoji: "✨" },
          { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4, emoji: "💰" },
          { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 5, emoji: "📱" },
        ],
      },
      {
        id: "r5",
        author: "Omar Al-Ghamdi",
        authorInitials: "OG",
        verified: true,
        date: "2024-02-28",
        rating: 5,
        comment: "Best 5G speeds I've experienced in Saudi. NEOM coverage is perfect. STC is genuinely leading Vision 2030 in telecom.",
        categories: [
          { name: "Service Quality", nameAr: "جودة الخدمة", score: 5, emoji: "⭐" },
          { name: "Wait Time", nameAr: "وقت الانتظار", score: 4, emoji: "⏱️" },
          { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 5, emoji: "🤝" },
          { name: "Cleanliness", nameAr: "النظافة", score: 5, emoji: "✨" },
          { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 5, emoji: "💰" },
          { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 5, emoji: "📱" },
        ],
      },
    ],
  },
  {
    id: "alrajhi",
    name: "Al Rajhi Bank",
    nameAr: "مصرف الراجحي",
    sector: "banking",
    sectorAr: "بنوك",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "platinum",
    overallScore: 4.6,
    reviewCount: 2108,
    rank: 2,
    rankChange: 0,
    logo: "R",
    description: "The world's largest Islamic bank by assets and Saudi Arabia's #1 retail bank.",
    descriptionAr: "أكبر بنك إسلامي في العالم من حيث الأصول وأفضل بنك للأفراد في المملكة العربية السعودية.",
    verified: true,
    featured: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.7, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 4.2, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.8, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.9, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.6, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 4.8, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "mobily",
    name: "Mobily",
    nameAr: "موبايلي",
    sector: "telecom",
    sectorAr: "اتصالات",
    city: "jeddah",
    cityAr: "جدة",
    tier: "gold",
    overallScore: 4.2,
    reviewCount: 892,
    rank: 3,
    rankChange: 1,
    logo: "M",
    description: "Etihad Etisalat - Mobily is Saudi Arabia's second-largest telecom provider.",
    descriptionAr: "اتحاد اتصالات - موبايلي هي ثاني أكبر مزود اتصالات في المملكة العربية السعودية.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.3, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 4.0, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.4, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.5, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.2, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 4.1, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "snb",
    name: "Saudi National Bank",
    nameAr: "البنك الأهلي السعودي",
    sector: "banking",
    sectorAr: "بنوك",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "gold",
    overallScore: 4.1,
    reviewCount: 1654,
    rank: 4,
    rankChange: -1,
    logo: "N",
    description: "Saudi Arabia's largest bank by assets, formed from the merger of NCB and Samba.",
    descriptionAr: "أكبر بنك في المملكة العربية السعودية من حيث الأصول.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.2, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.8, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.3, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.5, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.0, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 4.2, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "zain",
    name: "Zain KSA",
    nameAr: "زين السعودية",
    sector: "telecom",
    sectorAr: "اتصالات",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "gold",
    overallScore: 4.0,
    reviewCount: 567,
    rank: 5,
    rankChange: 3,
    logo: "Z",
    description: "Zain Saudi Arabia - modern telecom with competitive packages and wide coverage.",
    descriptionAr: "زين السعودية - اتصالات حديثة بباقات تنافسية وتغطية واسعة.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.0, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.9, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.1, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.3, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.2, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.9, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "riyadhbank",
    name: "Riyad Bank",
    nameAr: "بنك الرياض",
    sector: "banking",
    sectorAr: "بنوك",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "silver",
    overallScore: 3.8,
    reviewCount: 923,
    rank: 6,
    rankChange: -2,
    logo: "RB",
    description: "One of Saudi Arabia's oldest and most trusted banking institutions.",
    descriptionAr: "أحد أقدم المؤسسات المصرفية الأكثر ثقة في المملكة العربية السعودية.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 3.8, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.5, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.0, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.2, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 3.7, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.8, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "mcdonalds",
    name: "McDonald's KSA",
    nameAr: "ماكدونالدز السعودية",
    sector: "food",
    sectorAr: "مطاعم",
    city: "jeddah",
    cityAr: "جدة",
    tier: "gold",
    overallScore: 4.1,
    reviewCount: 3421,
    rank: 7,
    rankChange: 1,
    logo: "MC",
    description: "Saudi Arabia's most visited quick service restaurant chain.",
    descriptionAr: "سلسلة مطاعم الخدمة السريعة الأكثر زيارة في المملكة العربية السعودية.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.2, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 4.0, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.1, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.3, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.0, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 4.2, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "herfy",
    name: "Herfy",
    nameAr: "هرفي",
    sector: "food",
    sectorAr: "مطاعم",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "silver",
    overallScore: 3.9,
    reviewCount: 1876,
    rank: 8,
    rankChange: 0,
    logo: "H",
    description: "Saudi Arabia's homegrown fast food chain with over 400 locations.",
    descriptionAr: "سلسلة الوجبات السريعة السعودية الأصيلة مع أكثر من 400 فرع.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 3.9, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.8, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.0, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.1, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.2, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.5, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "kudu",
    name: "Kudu",
    nameAr: "كودو",
    sector: "food",
    sectorAr: "مطاعم",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "silver",
    overallScore: 3.7,
    reviewCount: 1234,
    rank: 9,
    rankChange: -1,
    logo: "K",
    description: "A beloved Saudi fast food brand known for authentic local flavors.",
    descriptionAr: "علامة تجارية سعودية للوجبات السريعة معروفة بنكهاتها المحلية الأصيلة.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 3.7, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.6, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 3.8, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.0, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.1, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.3, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "toyota",
    name: "Toyota KSA",
    nameAr: "تويوتا السعودية",
    sector: "automotive",
    sectorAr: "سيارات",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "gold",
    overallScore: 4.3,
    reviewCount: 789,
    rank: 10,
    rankChange: 2,
    logo: "T",
    description: "Abdullatif Jameel - exclusive distributor of Toyota vehicles in Saudi Arabia.",
    descriptionAr: "عبداللطيف جميل - الموزع الحصري لسيارات تويوتا في المملكة العربية السعودية.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.4, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 4.0, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.5, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.6, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.0, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 4.2, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "ikea",
    name: "IKEA Saudi Arabia",
    nameAr: "إيكيا السعودية",
    sector: "retail",
    sectorAr: "تجزئة",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "gold",
    overallScore: 4.2,
    reviewCount: 2341,
    rank: 11,
    rankChange: 1,
    logo: "IK",
    description: "IKEA Saudi Arabia - world-renowned furniture and home accessories at affordable prices.",
    descriptionAr: "إيكيا السعودية - أثاث وإكسسوارات منزلية بأسعار معقولة.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.2, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.8, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.3, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 4.5, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 4.6, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.9, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "noon",
    name: "Noon",
    nameAr: "نون",
    sector: "ecommerce",
    sectorAr: "تجارة إلكترونية",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "silver",
    overallScore: 3.6,
    reviewCount: 4521,
    rank: 12,
    rankChange: -3,
    logo: "N",
    description: "The Middle East's homegrown e-commerce platform, founded in Saudi Arabia.",
    descriptionAr: "منصة التجارة الإلكترونية الإقليمية السعودية المنشأ.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 3.5, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 3.8, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 3.6, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 3.5, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 3.9, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.8, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "arabiainsurance",
    name: "Tawuniya Insurance",
    nameAr: "التعاونية للتأمين",
    sector: "banking",
    sectorAr: "بنوك",
    city: "riyadh",
    cityAr: "الرياض",
    tier: "bronze",
    overallScore: 3.2,
    reviewCount: 876,
    rank: 13,
    rankChange: -2,
    logo: "TW",
    description: "Saudi Arabia's largest insurance company providing comprehensive coverage.",
    descriptionAr: "أكبر شركة تأمين في المملكة العربية السعودية.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 3.2, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 2.9, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 3.4, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 3.8, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 3.0, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 3.1, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "sadafco",
    name: "Al Baik",
    nameAr: "البيك",
    sector: "food",
    sectorAr: "مطاعم",
    city: "jeddah",
    cityAr: "جدة",
    tier: "platinum",
    overallScore: 4.8,
    reviewCount: 5632,
    rank: 14,
    rankChange: 4,
    logo: "AB",
    description: "Saudi Arabia's iconic fried chicken restaurant - a national institution since 1974.",
    descriptionAr: "مطعم الدجاج المقلي الأيقوني في المملكة العربية السعودية منذ عام 1974.",
    verified: true,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 4.9, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 4.5, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 4.8, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 5.0, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 5.0, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 4.5, emoji: "📱" },
    ],
    reviews: [],
  },
  {
    id: "badservice",
    name: "Local Taxi Co.",
    nameAr: "شركة التاكسي المحلية",
    sector: "automotive",
    sectorAr: "سيارات",
    city: "dammam",
    cityAr: "الدمام",
    tier: "redflag",
    overallScore: 1.8,
    reviewCount: 234,
    rank: 15,
    rankChange: -5,
    logo: "LT",
    description: "Local taxi service in Dammam region.",
    descriptionAr: "خدمة تاكسي محلية في منطقة الدمام.",
    verified: false,
    categories: [
      { name: "Service Quality", nameAr: "جودة الخدمة", score: 1.8, emoji: "⭐" },
      { name: "Wait Time", nameAr: "وقت الانتظار", score: 1.5, emoji: "⏱️" },
      { name: "Staff Attitude", nameAr: "تعامل الموظفين", score: 1.9, emoji: "🤝" },
      { name: "Cleanliness", nameAr: "النظافة", score: 2.1, emoji: "✨" },
      { name: "Value for Money", nameAr: "القيمة مقابل السعر", score: 1.7, emoji: "💰" },
      { name: "Digital Experience", nameAr: "التجربة الرقمية", score: 2.0, emoji: "📱" },
    ],
    reviews: [],
  },
];

export const getBusiness = (id: string): Business | undefined =>
  businesses.find((b) => b.id === id);

export const getTopBusinesses = (count: number = 5): Business[] =>
  [...businesses].sort((a, b) => b.overallScore - a.overallScore).slice(0, count);

export const getLeaderboard = (sector?: string): Business[] => {
  const filtered = sector && sector !== "all"
    ? businesses.filter((b) => b.sector === sector)
    : businesses;
  return [...filtered].sort((a, b) => b.overallScore - a.overallScore);
};
